### ISSUE TITLE
About tutorial

### ISSUE THREAD

**Issue by EasonWang01** [Rhadow/webpack-boiler-plate#1]
Hi，this boilerplate is really good,do you have a tutorial about creating this? thanks a lot.

**Comment by Rhadow** [comment]
Hi Eason,

Unfortunately, I am not planning on writing a tutorial in English about this boilerplate.
However, the following link helped me a lot on building this repo:
[Webpack cookbook](https://christianalfoni.github.io/react-webpack-cookbook/)

If you can read Chinese, you are welcome to read some of my articles on how to build this boilerplate in my [blog](http://rhadow.github.io/).

**Comment by EasonWang01** [comment]
Hi,could I ask something that I can figure out that

```
   output: {
        path: buildPath,
        filename: 'bundle.js',
        publicPath: '/build/'
    }
```

It seems there is no build folder inside this repo,I only found bundle.js inside server folder?

**Comment by Rhadow** [comment]
The dist folder will be generated in production mode.
In development mode, all bundled items are stored in memory and that build folder was just a placeholder since webpack required output property in the config object.
You can check webpack official website for further information.
